// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: goods.proto

package goods

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GoodsService service

func NewGoodsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GoodsService service

type GoodsService interface {
	GetGoodsDetails(ctx context.Context, in *RequestGoods, opts ...client.CallOption) (*ResponseGoods, error)
}

type goodsService struct {
	c    client.Client
	name string
}

func NewGoodsService(name string, c client.Client) GoodsService {
	return &goodsService{
		c:    c,
		name: name,
	}
}

func (c *goodsService) GetGoodsDetails(ctx context.Context, in *RequestGoods, opts ...client.CallOption) (*ResponseGoods, error) {
	req := c.c.NewRequest(c.name, "GoodsService.GetGoodsDetails", in)
	out := new(ResponseGoods)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoodsService service

type GoodsServiceHandler interface {
	GetGoodsDetails(context.Context, *RequestGoods, *ResponseGoods) error
}

func RegisterGoodsServiceHandler(s server.Server, hdlr GoodsServiceHandler, opts ...server.HandlerOption) error {
	type goodsService interface {
		GetGoodsDetails(ctx context.Context, in *RequestGoods, out *ResponseGoods) error
	}
	type GoodsService struct {
		goodsService
	}
	h := &goodsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GoodsService{h}, opts...))
}

type goodsServiceHandler struct {
	GoodsServiceHandler
}

func (h *goodsServiceHandler) GetGoodsDetails(ctx context.Context, in *RequestGoods, out *ResponseGoods) error {
	return h.GoodsServiceHandler.GetGoodsDetails(ctx, in, out)
}
